# -*- coding: utf-8 -*-
"""llm_by_me.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuPeHfCBbFyqCiUQ6ghhMcK1Z3K22Y00
"""

import os

os.chdir("/content")

print("Current working directory:", os.getcwd())

import os
import sys
import shutil
import subprocess
import torch

# Check GPU resources
subprocess.run(["nvidia-smi"])

print("PyTorch Version:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())
print("GPU Count:", torch.cuda.device_count())

for i in range(torch.cuda.device_count()):
    p = torch.cuda.get_device_properties(i)
    print(f"GPU {i}: {torch.cuda.get_device_name(i)} ({p.total_memory / 1024**3:.2f} GB)")

# Remove existing folder to prevent duplication or stale files
# repo_dir = "llm_by_me"
if os.path.exists("llm_by_me"):
    # # Move out of the directory if the notebook working directory is inside it
    # if os.getcwd().endswith(repo_dir):
    #     os.chdir("..")
    # shutil.rmtree(repo_dir)

# Clone fresh repository
    subprocess.run(["git", "clone", "-b", "V1", "https://github.com/shra1-cmd/llm_by_me.git"])

# Change directory and check status
os.chdir("llm_by_me")
subprocess.run(["git", "log", "-1", "--oneline"])

import sys
import subprocess

# Install requirements and testing tools
subprocess.run([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
subprocess.run([sys.executable, "-m", "pip", "install", "pytest", "dataloader"])

#drive.flush_and_unmount()

import os
import shutil
import subprocess

# ============================================================
# Mount Google Drive
# ============================================================

try:
    from google.colab import drive
    drive.mount("/content/drive")
except ImportError:
    print("Skipping Google Drive mount (Not in Colab).")


# ============================================================
# DRIVE DATA
# ============================================================

drive_base = "/content/drive/MyDrive/llm_by_me_data"

drive_tokens = os.path.join(drive_base, "tokens")
drive_tokenizer = os.path.join(drive_base, "tokenizer")


# ============================================================
# LOCAL DATA
# ============================================================

local_tokens = "/content/llm_by_me/data/tokens"
local_tokenizer = "/content/llm_by_me/data/tokenizer"

os.makedirs(local_tokens, exist_ok=True)
os.makedirs(local_tokenizer, exist_ok=True)


# ============================================================
# COPY TOKEN FILES
# ============================================================

for filename in ["train.bin", "validation.bin"]:

    src = os.path.join(drive_tokens, filename)
    dst = os.path.join(local_tokens, filename)

    if os.path.exists(src):
        shutil.copy2(src, dst)
        print(f"✓ Copied {filename}")
    else:
        raise FileNotFoundError(
            f"Could not find:\n{src}"
        )


# ============================================================
# COPY TOKENIZER
# ============================================================

src = os.path.join(
    drive_tokenizer,
    "tokenizer.json"
)

dst = os.path.join(
    local_tokenizer,
    "tokenizer.json"
)

if os.path.exists(src):
    shutil.copy2(src, dst)
    print("✓ Copied tokenizer.json")
else:
    raise FileNotFoundError(
        f"Could not find:\n{src}"
    )


# ============================================================
# FINAL VERIFICATION
# ============================================================

print("\n" + "=" * 60)
print("LOCAL DATA READY")
print("=" * 60)

print("\nTokens:")
subprocess.run(
    ["ls", "-lh", local_tokens]
)

print("\nTokenizer:")
subprocess.run(
    ["ls", "-lh", local_tokenizer]
)

import os
import sys
import subprocess

# Set environment path so Python modules import correctly
env = os.environ.copy()
env["PYTHONPATH"] = os.getcwd()

# Run pytest suite
print("--- Running Tests ---")
subprocess.run(["pytest", "tests/", "-v"], env=env)

# Run training benchmark
print("\n--- Running Benchmark Script ---")
subprocess.run([sys.executable, "scripts/benchmark_training.py"], env=env)

import os
import sys
import subprocess
import time

# ------------------------------------------------------------
# Environment
# ------------------------------------------------------------

env = os.environ.copy()
env["PYTHONPATH"] = os.getcwd()
env["PYTHONUNBUFFERED"] = "1"

# ------------------------------------------------------------
# Start training
# ------------------------------------------------------------

print("=" * 70)
print("🚀 STARTING V1 TRAINING")
print("=" * 70)

start_time = time.time()

process = subprocess.Popen(
    [sys.executable, "-u", "scripts/train_v1.py"],
    env=env,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True,
    bufsize=1,
)

# ------------------------------------------------------------
# Stream output LIVE
# ------------------------------------------------------------

for line in process.stdout:
    print(line, end="", flush=True)

# Wait for process
return_code = process.wait()

# ------------------------------------------------------------
# Final information
# ------------------------------------------------------------

elapsed = time.time() - start_time

print()
print("=" * 70)

if return_code == 0:
    print("✅ TRAINING FINISHED")
else:
    print(f"❌ TRAINING FAILED — return code: {return_code}")

print(f"⏱️ Total time: {elapsed / 60:.2f} minutes")
print(f"⏱️ Total time: {elapsed / 3600:.2f} hours")

print("=" * 70)